const USER = {
  LOAD: 'REQUEST_USERS_DATA',
  LOAD_SUCCESS: 'RECEIVE_USERS_DATA',
  FILTERED_DATA: 'SET_FILTER_DATA',
  CART_DATA: 'ADD_CART_DATA',
  LIKE_DATA: 'ADD_LIKE_DATA',
  REMOVE_CART:'REMOVE_CART_DATA',
  IDC_CART:'IDC_CART'
};

export default USER;
